function Hd = del
%DEL Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the DSP System Toolbox 8.3.
%
% Generated on: 09-Nov-2012 21:30:55
%

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

N    = 10;       % Order
Fc   = 150;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = ;
Hd = dfilt.dffir(fir1(10, 150/(10000/2), 'low', kaiser(10+1, 0.5), 'scale'));

% [EOF]
